language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t barreto-lucas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  barreto-lucas/docker-react npm run test
